fix

diff --git a/autoinstall_rke2/user-data b/autoinstall_rke2/user-data
--- a/autoinstall_rke2/user-data
+++ b/autoinstall_rke2/user-data
@@ -45,38 +45,38 @@ autoinstall:
         -   path: /opt/setup.sh
             permissions: 0770
             content: |
-            #!/bin/bash
-            set -x
-            set -e
+                #!/bin/bash
+                set -x
+                set -e
 
-            if [[ "$1" != "server" && "$1" != "agent" ]]; then
-                echo "Invalid argument. Usage: $0 [server|agent]"
-                exit 1
-            fi
+                if [[ "$1" != "server" && "$1" != "agent" ]]; then
+                    echo "Invalid argument. Usage: $0 [server|agent]"
+                    exit 1
+                fi
 
-            echo "Running setup as $(whoami)"
+                echo "Running setup as $(whoami)"
 
-            # echo "Resize disks (all nodes)"
-            # lvresize -rl +100%FREE /dev/vgroot/lvroot
+                # echo "Resize disks (all nodes)"
+                # lvresize -rl +100%FREE /dev/vgroot/lvroot
 
-            echo "Install iptables (required for nginx ingress controller) (all nodes)"
-            apt install iptables -y
+                echo "Install iptables (required for nginx ingress controller) (all nodes)"
+                apt install iptables -y
 
-            echo "Set up Longhorn dependencies (all nodes)"
-            apt install open-iscsi nfs-common -y
-            systemctl start iscsid
+                echo "Set up Longhorn dependencies (all nodes)"
+                apt install open-iscsi nfs-common -y
+                systemctl start iscsid
 
-            systemctl daemon-reload
+                systemctl daemon-reload
 
-            if [ "$1" = "server" ]; then
-                echo "Running server setup"
-                systemctl enable --now rke2-server
-                systemctl start rke2-server.service
-            elif [ "$1" = "agent" ]; then
-                echo "Running agent setup"
-                systemctl enable --now rke2-agent
-                systemctl start rke2-agent.service
-            fi
+                if [ "$1" = "server" ]; then
+                    echo "Running server setup"
+                    systemctl enable --now rke2-server
+                    systemctl start rke2-server.service
+                elif [ "$1" = "agent" ]; then
+                    echo "Running agent setup"
+                    systemctl enable --now rke2-agent
+                    systemctl start rke2-agent.service
+                fi
 
         -   path: /etc/rancher/rke2/config.yaml
             owner: root:root
